# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
 
# Inserts a blank line between shell prompts
add_newline = true
 
[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
format = " ğŸ•™ $duration($style) "
 
[docker_context]
format = "via [$symbol$context]($style) "
symbol="ğŸ³ "
detect_files=["docker-compose.yml", "docker-compose.yaml","docker-compose.dev.yaml", "docker-compose.dev.yml", "Dockerfile"]
detect_folders=["docker"]
 
[username]
format = "[$user]($style) on "